services:
  ros2_node1:
    image: osrf/ros:humble-desktop-full-jammy
    container_name: ros2_humble_jammy_node1
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               source /pubsub/install/setup.bash &&
               ros2 run pubsub talker --log-level"
    volumes:
      - ./pubsub:/pubsub
      - ./install:/pubsub/install
    networks:
      - ros_network

  ros2_node2:
    image: osrf/ros:humble-desktop-full-jammy
    container_name: ros2_humble_jammy_node2
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
                source /pubsub/install/setup.bash &&
                ros2 run pubsub listener --log-level"
    volumes:
      - ./pubsub:/pubsub
      - ./install:/pubsub/install
    networks:
      - ros_network

networks:
  ros_network:
    driver: bridge
